### ISSUE TITLE
hal/nrf_i2s.h - No such file or directory

### ISSUE THREAD

**Issue by ktorimaru** [tensorflow/tflite-micro-arduino-examples#167]
Trying to compile hello_world I get:

??????/libraries/Arduino_TensorFlowLite/src/peripherals/i2s_nrf52840.cpp:22:10: fatal error: hal/nrf_i2s.h: No such file or directory
 #include <hal/nrf_i2s.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Raspberry Pi Pico.

**Comment by ddavis-2015** [comment]
@ktorimaru 

Thank you for bringing this issue to our attention.  Currently, the arduino-examples repository only has official support for a single board.  That board is the Arduino Nano 33 BLE Sense (using the NRF52840 SOC).  No other board or platform is currently officially supported by the codebase.

You are welcome to make modifications to your clone/fork of the codebase in order to use the platform or board of your choice.

I would suggest, as a quick solution to your issue, wrapping the code in i2s_nrf52840.cpp with the following preprocessor directive: `#ifdef ARDUINO_ARCH_NRF52840`

An example of such a modification can be found here: https://github.com/ddavis-2015/tflite-micro-arduino-examples/blob/25b752ea34ef10ba5dd01b1c279e9430d091325d/src/peripherals/i2s_nrf52840.cpp
