### ISSUE TITLE
Library problem of abs calculation

### ISSUE THREAD

**Issue by konegen** [tensorflow/tflite-micro-arduino-examples#179]
I get the following error when I compile my Arduino project. I included both the Arduino and the TensorFlow library:

```
Arduino\libraries\Arduino_TensorFlowLite\src/tensorflow/lite/kernels/internal/quantization_util.h: In function 'tflite::QuantizationParams tflite::ChooseQuantizationParams(double, double, bool)':
AppData\Local\Arduino15\packages\arduino\hardware\mbed\3.3.0\cores\arduino/Arduino.h:63:16: error: expected unqualified-id before '(' token
 #define abs(x) ((x)>0?(x):-(x))
                ^
Arduino\libraries\Arduino_TensorFlowLite\src/tensorflow/lite/kernels/internal/quantization_util.h:67:12: note: in expansion of macro 'abs'
       std::abs(qmin_double) + std::abs(rmin / scale);
```
It looks like there is a compilation error and a problem with the definition of the "abs" function in the "Arduino.h" file, which is conflicting with the "abs" function used in the "quantization_util.h" file.

Did someone also experience such error?
Can anyone help me with that error?

Thanks

**Comment by ddavis-2015** [comment]
@konegen 

Your feedback regarding the TensorFlow Lite Micro (TFLM) codebase is much appreciated.

Please make sure you have the latest update to the [tflite-micro-arduino-examples](https://github.com/tensorflow/tflite-micro-arduino-examples) repository.  This issue was resolved through PR #170 approximately two weeks ago.  All example applications in the repository compile correctly.

If this issue has occurred while creating your own application, then you will continue to encounter the compilation error. Mixing TFLM header files together in the same application with the Arduino.h header file, will require the following code:
```
#include <Arduino.h>
#undef abs
```

Alternatively you may separate out all TFLM specific code in your application to a new file with the `.cpp` suffix.  This new file should not include any Arduino header files.

Please feel free to reopen this issue should you wish to supply any additional information.
